Fix Chinese Search Bug
CollegesChat/university-information pull request #245
Opened 2024-06-29 21:23 UTC by 7emotions

- [x] 我已阅读说明，并确认此 PR 不适用问卷提交或修改。

## Description

As discussed in #138 , at the moment searching with full university name does not work.

## Bug Reproduce

As shown in the following figures, NJUST, for example, was included in the dataset, but no corresponding results were found in the search box.

![image](https://github.com/CollegesChat/university-information/assets/42567930/71b08935-c9b1-42bb-83cd-0b0eadb2de05)

![image](https://github.com/CollegesChat/university-information/assets/42567930/c96986b7-a3f7-4fdf-bc23-5147be866191)

## Solution Effect

As shown in the following figure, NJUST, including its multiple campuses, has been correctly displayed. 

![image](https://github.com/CollegesChat/university-information/assets/42567930/e94c8293-60f5-487b-853e-825a0b5f4b7c)

In addition, searching suggestions are provided while typing.

![image](https://github.com/CollegesChat/university-information/assets/42567930/b551aae2-615b-4323-b31e-8af9a0878fd4)

> PS: It occurs that some samples with too long title name are unable to be wriiten when building site. Thus, I take the liberty of filtering them out. However, in terms of results, all those samples filtered out are negative sample.

2024-07-03 18:38 UTC, 7emotions commented
@aisuneko

2024-07-17 14:21 UTC, Rachel030219 requested changes
why so many minor and completely irrelevant changes to code style

2024-07-18 08:33 UTC, 7emotions commented
Commits have been reset. I am very sorry for the additional workload before.

2024-07-18 08:51 UTC, 7emotions commented on questionnaires/main.py
> +
The reason for the modification is that error was encountered while writing files on account of long filename.

2024-07-18 08:53 UTC, 7emotions commented on questionnaires/main.py
> +
The reason for the modification is that an error was encountered while writing files on account of long filename. This is not relevant to the main work of this PR.

2024-07-18 09:04 UTC, 7emotions commented
Additionally, in order to implement keyword search, the source file of mkdocs needs to be modified to use jieba for Chinese word segmentation. However, such modification is not in the repository code, and I want to know whether this solution is acceptable.

![微信图片_20240718170053](https://github.com/user-attachments/assets/e8d1cd3d-c45f-494c-b263-2f52a9f34579)

2026-03-22 06:54 UTC, merged